### ISSUE TITLE
E_ROUTE_NOT_FOUND: Route not found GET

### ISSUE THREAD

**Issue by kimoduor** [evdevru/casino#5]
I have installed the client well but the server gives me the error. Ca I get any help?

**Comment by evdevru** [comment]
> I have installed the client well but the server gives me the error. Ca I get any help?

Check logs, give me more info. I cant solve "i have error" without them

**Comment by Yalanix** [comment]
Hi, 

Would it be possible to get the full site, with all the games? Deposit can be made through crypto? The site looks amazing, I am learning web development at my college too but im not anywhere near to make such a website. 

If yes, how much would you ask?

Thank you

**Comment by evdevru** [comment]
> HttpException E_ROUTE_NOT_FOUND: Route not found GET /

You are following the route of the server, not the client. Port for client by default 3000

**Comment by kimoduor** [comment]
```
[HMR] connected
127.0.0.1:3333/api/v1/auth/user:1          Failed to load resource: the server responded with a status of 401 (Unauthorized)
vue-router.esm.js?8c4f:16 [vue-router] Route with name 'free-coins' does not exist
warn @ vue-router.esm.js?8c4f:16
nuxt-socket-io.js?2120:969 [nuxt-socket-io]: connect main http://127.0.0.1:3333/crash Object
vue-router.esm.js?8c4f:16 [vue-router] Route with name 'free-coins' does not exist
warn @ vue-router.esm.js?8c4f:16
```
