### ISSUE TITLE
error  cannot find module

### ISSUE THREAD

**Issue by rtxphantom** [evdevru/casino#8]
Error: Cannot find module '/home/admin/casino/server/node_modules/@adonisjs/mail/providers/MailProvider'

1 requireStack
  /home/admin/casino/server/node_modules/require-stack/src/index.js:44

2 anonymous
  /home/admin/casino/server/node_modules/@adonisjs/fold/src/Registrar/index.js:104

this is after I fixed issues using npm audit fix --force

**Comment by evdevru** [comment]
Please read how is working npm audit fix. Closed
